// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRx_xQyBXGLWzHX-tjmv76RcVswOU_oQ',
    appId: '1:589812618344:web:c38e364136e387c30217dd',
    messagingSenderId: '589812618344',
    projectId: 'social-media-app-c4b3a',
    authDomain: 'social-media-app-c4b3a.firebaseapp.com',
    storageBucket: 'social-media-app-c4b3a.firebasestorage.app',
    measurementId: 'G-HCTDXCHHP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdtXqbBidhYxLveuEOZS55O5eJl0xsQk',
    appId: '1:589812618344:android:1c9dc47792f6c2a50217dd',
    messagingSenderId: '589812618344',
    projectId: 'social-media-app-c4b3a',
    storageBucket: 'social-media-app-c4b3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ee04z4R8F-WYBafISv49SUpr79aZLJ8',
    appId: '1:589812618344:ios:44442e657d1919520217dd',
    messagingSenderId: '589812618344',
    projectId: 'social-media-app-c4b3a',
    storageBucket: 'social-media-app-c4b3a.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
